---
name: "Build TMKMS release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Specify the version"
        required: true
        default: "v1.0.0"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest-l"